--- #YAML:1.0
name: Graph-Easy-As_svg
version: 0.16
version_from: lib/Graph/Easy/As_svg.pm
license: gpl
distribution_type: module
generated_by: Graph-Easy-As_svg version 0.16
installdirs: site
requires:
  Graph::Easy: 0.38
